# Paris Metropolitan, an evolution
The goal of this notebook is to compare the database in xlsx format with the updated geojson file and to ouput a corresponding csv file that includes new information added

In [1]:
#imports
import pandas as pd
import numpy as np
import json

In [2]:
#path to database
json_database_path = r'paris_metropolitan_evolution_db_updated.geojson'

In [3]:
#open xlsx file and json file
paris_metro_xls_db = pd.read_excel('paris_metropolitan_evolution_db.xlsx', skiprows=1)
paris_metro_json_db = json.load(open(json_database_path))

In [4]:
#iterate through both files in order to update the first database in xlsx format with the second one
for index, row in paris_metro_xls_db.iterrows() :
    for feature in paris_metro_json_db['features'] :
        if row['stop_id'] == feature['properties']['stop_id'] :
            paris_metro_xls_db.loc[index,'stop_info'] = feature['properties']['stop_info']
            paris_metro_xls_db.loc[index,'open_date'] = feature['properties']['open_date']
            paris_metro_xls_db.loc[index,'close_date'] = feature['properties']['close_date']
            paris_metro_xls_db.loc[index, 'ratp_id'] = feature['properties']['ratp_id']
            break
paris_metro_xls_db

,x,y,stop_id,stop_name,stop_line,stop_info,open_date,close_date,start_map,end_map,ratp_id
0,2.283876,48.876717,19081,Porte Maillot,1,None,1900-07-19,NaN,1908,1950,2433.0
1,2.277594,48.872253,19082,Porte Dauphine,2 Nord,None,1900-12-13,NaN,1908,1908,2414.0
2,2.277466,48.870780,19083,Porte Dauphine,2 Nord,None,1900-12-13,NaN,1908,1908,2414.0
3,2.285599,48.869948,19084,Victor Hugo,2 Nord,The station is named after Victor Hugo (1802-1...,1900-12-13,NaN,1908,1908,2504.0
4,2.288289,48.875327,19085,Obligado,1,None,1900-07-19,1948-05-25,1908,1915,2048.0
5,2.295141,48.874751,19086,Etoile,2 Nord,None,1900-07-19,NaN,1908,1908,2030.0
6,2.298535,48.878081,19087,Ternes,2 Nord,None,1902-10-07,NaN,1908,1908,1684.0
7,2.303274,48.879170,19088,Courcelles,2 Nord,None,1902-10-07,NaN,1908,1908,2179.0
8,2.308141,48.880514,19089,Monceau,2 Nord,None,1902-10-07,NaN,1908,1908,1822.0
9,2.313073,48.881219,190810,Villiers,2 Nord,None,1902-10-07,NaN,1908,1908,1630.0
10,2.292195,48.870588,190811,Kleber,2 Sud,None,1900-10-02,NaN,1908,1908,2234.0
11,2.300072,48.871421,190812,Alma,1,The station was named after the Battle of Alma...,1900-07-19,1920-05-27,1908,1915,1961.0
12,2.289762,48.867258,190813,Boissi√®re,2 Sud,None,1900-10-02,NaN,1908,1908,2122.0
13,2.319413,48.882179,190814,Rome,2 Nord,None,1902-10-07,NaN,1908,1908,1707.0
14,2.304939,48.870012,190815,Marbeuf,1,None,1900-07-19,1946-10-30,1908,1915,1946.0
15,2.287648,48.864184,190816,Trocadero,2 Sud,"For the Exposition Internationale of 1937, the...",1900-10-02,NaN,1908,1908,1687.0
16,2.284766,48.858676,190817,Passy,2 Sud,None,1903-11-05,NaN,1908,1908,1780.0
17,2.313457,48.867386,190818,Champs-Elys√©es,1,The station was named for the Elysian Fields -...,1900-07-19,NaN,1908,1915,2544.0
18,2.327738,48.883973,190819,Clichy,2 Nord,None,1902-10-07,NaN,1908,1908,1796.0
19,2.331773,48.883973,190820,Blanche,2 Nord,The station is home to the famous Moulin Rouge...,1902-10-07,NaN,1908,1908,2120.0
20,2.337408,48.882692,190821,Pigalle,2 Nord,None,1902-10-07,NaN,1908,1908,1792.0
21,2.322871,48.875967,190822,Gare Saint-Lazare,3,None,1904-10-19,NaN,1908,1950,2468.0
22,2.288993,48.854001,190823,Grenelle,2 Sud,None,1906-04-24,NaN,1908,1908,2069.0
23,2.324472,48.865785,190824,Concorde,1,Place de la Concorde was designed by Ange-Jacq...,1900-07-19,NaN,1908,1950,2172.0
24,2.329916,48.864120,190825,Tuileries,1,"Filled with fountains, classical sculptures an...",1900-07-19,NaN,1908,1950,1688.0
25,2.336768,48.862070,190826,Palais Royal,1,"Konwn initially as the Palais-Cardinal, a pers...",1900-07-19,NaN,1908,1950,2383.0
26,2.329083,48.873278,190827,Caumartin,3,None,1904-10-19,NaN,1908,1915,2286.0
27,2.332605,48.870908,190828,Op√©ra,3,Designed in 1860 by Charles Garnier - then an ...,1904-10-19,NaN,1908,1950,2314.0
28,2.344261,48.883396,190829,Anvers,2 Nord,"The station is home to √âlys√©e Montmartre, a ba...",1902-10-07,NaN,1908,1908,2046.0
29,2.349384,48.884357,190830,Barb√®s,4,"In this station, the French resistance launche...",1903-01-31,NaN,1908,1908,2061.0
...,...,...,...,...,...,...,...,...,...,...,...
394,2.320886,48.841641,190858,Maine,5,None,1906-04-24,1933-06-30,1915,1915,4944.0
395,2.312251,48.841473,190859,Pasteur,5,None,1906-04-24,NaN,1915,1915,2392.0
396,2.312251,48.841473,190859,Pasteur,6,None,1906-04-24,NaN,1950,1950,2392.0
397,2.359167,48.885145,190862,La Chapelle,2,None,1903-01-31,NaN,1915,1950,2235.0
398,2.364209,48.885051,190863,Aubervilliers,2,None,1903-01-31,1946-02-10,1915,1950,2484.0
399,2.370698,48.877629,190867,Combat,2,None,1903-01-31,1945-08-19,1915,1915,1978.0
400,2.376206,48.872120,190870,Belleville,2,None,1903-01-31,NaN,1915,1950,2115.0
401,2.379754,48.868993,190871,Couronnes,2,The station was the site of a fire and stamped...,1903-01-31,NaN,1915,1950,2128.0
402,2.383489,48.866612,190872,Menilmontant,2,None,1903-01-31,NaN,1915,1950,2351.0
403,2.389324,48.858582,190875,Philippe-Auguste,2,None,1903-01-31,NaN,1915,1950,2398.0
404,2.393619,48.856248,190877,Bagnolet,2,The station will be later renamed from Bagnole...,1903-01-31,1970-09-13,1915,1950,2041.0
405,2.396607,48.852467,190886,Avron,2,None,1903-04-02,NaN,1915,1950,2107.0
406,2.356459,48.831693,1908103,Italie,5,None,1906-04-24,NaN,1915,1915,1794.0
407,2.356459,48.831693,1908103,Italie,6,None,1906-04-24,NaN,1950,1950,1794.0
408,2.350344,48.829499,1908104,Corvisart,5,None,1906-04-24,NaN,1915,1915,2177.0
409,2.350344,48.829499,1908104,Corvisart,6,None,1906-04-24,NaN,1950,1950,2177.0
410,2.343855,48.830853,1908105,La Glaci√®re,5,None,1906-04-24,NaN,1915,1915,2217.0
411,2.343855,48.830853,1908105,La Glaci√®re,6,None,1906-04-24,NaN,1950,1950,2217.0
412,2.337553,48.832440,1908106,Saint-Jacques,5,None,1906-04-24,NaN,1915,1915,2520.0
413,2.337553,48.832440,1908106,Saint-Jacques,6,None,1906-04-24,NaN,1950,1950,2520.0
414,2.330457,48.838789,1908108,Raspail,5,None,1910-01-09,NaN,1915,1915,1763.0
415,2.330457,48.838789,1908108,Raspail,6,None,1910-01-09,NaN,1950,1950,1763.0
416,2.332044,48.834634,1908111,Denfert-Rochereau,5,None,1909-10-30,NaN,1915,1915,2187.0
417,2.332044,48.834634,1908111,Denfert-Rochereau,6,None,1909-10-30,NaN,1950,1950,2187.0
418,2.324855,48.840726,1908115,Edgar-Quinet,5,None,1906-04-24,NaN,1915,1915,2255.0
419,2.324855,48.840726,1908115,Edgar-Quinet,6,None,1906-04-24,NaN,1950,1950,2255.0
420,2.386529,48.862913,1908124,P√®re-Lachaise,2,None,1904-10-19,NaN,1915,1950,2394.0
421,2.394157,48.848427,1908125,Nation,2,Widely known for having the most active guillo...,1900-07-19,NaN,1915,1950,2371.0
422,2.294593,48.874231,1908130,Etoile,5,None,1900-07-19,NaN,1915,1915,2030.0
423,2.294593,48.874231,1908130,Etoile,6,None,1900-07-19,NaN,1950,1950,2030.0

In [5]:
#write a csv file based on the updated xlsx database
file_name = "final_database_files/paris_metropolitan_evolution_db.csv"
paris_metro_xls_db.to_csv(file_name, sep='\t', encoding='utf-8')